            - name: Python flake8 Lint
  # You may pin to the exact commit or the version.
  # uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba
  uses: py-actions/flake8@v2.3.0
  with:
    # Path to source file or directory (default='.')
    path: # optional, default is .
    # Boolean for pip upgrade prior to flake8 installation (default='false')
    update-pip: # optional, default is false
    # Comma delimited list of ignored flake8 rule codes (optional)
    ignore: # optional, default is none
    # Comma delimited list of excluded paths (optional)
    exclude: # optional, default is none
    # Integer value representing max acceptable line length (optional)
    max-line-length: # optional, default is none
    # flake8 arguments for test execution (optional)
    args: # optional, default is none
    # The flake8 version for tests (optional, default='latest')
    flake8-version: # optional, default is latest
    # List of flake8 plugins for pip installation prior to flake8 execution
    plugins: # optional, default is none
          
